name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # triggers the workflow manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        ruby-version: ['2.7.1']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: ruby test/customer_success_balancing_test.rb